apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api-deployment
  labels:
    app: users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
      - name: users-api
        image: users-api:8.0.1
        ports:
        - containerPort: 8080
        env:
        - name: APP_MONGODB_CS
          value: mongodb://admin:m0ng0d4t4@192.168.1.254:27019
---
apiVersion: v1
kind: Service
metadata:
  name: users-api-service
spec:
  selector:
    app: users-api
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8080
  type: LoadBalancer